[package]
name = "tcp_client"
version = "0.1.0"
authors = ["Simon Pannek <simon.pannek@tum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
